apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/maxxam123/platf04.git
        revision: HEAD
        directories:
          - path: 05_helm/NAME/02_monitor/*

