on:
  push:
    branches:
    - main
    paths:
    - 'sync2/nihao2.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          ls -la
