on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/test'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/SERVICE/NAME/   ### 01_lambda == SERVICE  

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       # id: init
       run: |
         cp ../../../../02_tmp/SERVICE/PROVIDER/01_variables.tf .
         cp ../../../../02_tmp/SERVICE/PROVIDER/03_main.tf .
         sh scripts/script_del.sh
         cp ../../../../03_pro/PROVIDER/02_provider.tf .
         echo "LS"
         ls -la

         cd ../../../..
         git clone https://github.com/maxxam123/platf04.git
         rm -rf platf04/.github/workflows/SERVICE-NAME.yaml
         rm -rf platf04/01_infra/SERVICE/PROVIDER/NAME
         rm -rf platf04/04_git/PROVIDER/NAME
         echo "LAST........................."
      # rm -rf platf04/.github/workflows/01_NAME.yaml
     #    terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     #- name: Terraform Plan
     #  run: terraform plan -lock=false

     #- name: Terraform Destroy
     #  run: terraform destroy -auto-approve -input=false -lock=false
     - name: Pushes to another repository
       uses: cpina/github-action-push-to-another-repository@main
       env:
         API_TOKEN_GITHUB: ${{ secrets.NEWPLAT }}
       with:
         source-directory: "platf04"
         destination-github-username: "maxxam123"
         destination-repository-name: "platf04"
         user-email: hennighausenmax@gmail.com
         target-branch: main
