on:
 push:
   branches:
   - main
   paths:
   - '01_infra/SERVICE/PROVIDER/NAME/*'   #### 01_lambda == SERVICE

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/SERVICE/PROVIDER/NAME/  #### 01_lambda == SERVICE

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       id: init
       run: |
         cp ../../../../02_tmp/SERVICE/PROVIDER/01_variables.tf .
         cp ../../../../02_tmp/SERVICE/PROVIDER/03_main.tf .
         sh scripts/script.sh
         cp ../../../../03_pro/PROVIDER/02_provider.tf .
         
         echo "LS"
         ls -la
         echo "EFS"
         cat 08_efs.tf
     #    terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     #- name: Terraform Plan
     #  run: terraform plan -lock=false

     #- name: Terraform Apply
     #  run: terraform apply -auto-approve -input=false -lock=false
