apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME-Ingress
  namespace: ingress
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: https://kubernetes.default.svc
  project: default
  source:
    path: 
    repoURL: https://gitlab.com/maxxam123/platform01.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
