on:
 push:
   branches:
   - main
   paths:
   - '01_infra/vpc/NAME/02_provider.tf'


env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: 01_infra/vpc/NAME/

   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0

     - name: Terraform init
       id: init
       run: |
         echo "THIS IS GCP"
         cp ../../../02_tmp/02_vpc/* .
         sed -i -e "s/RESOURCE/NAME/g" main.tf
         cat main.tf
         terraform init -backend-config="bucket=dunhuang-gansu-terraform-state"
       
     - name: Terraform Plan
       run: terraform plan -lock=false

     #- name: Terraform Apply
     #  run: terraform apply -auto-approve -input=false -lock=false
