on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/01_lambda'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            git clone https://github.com/maxxam123/platf04.git

            START=$( sed -n 1p 03_trigger/01_lambda )
            NAME=$( sed -n 1p 01_infra/lambda/$START/values )
            COUNT=$( sed -n 3p 01_infra/lambda/$START/values )
            PROVIDER=$( sed -n 2p 01_infra/lambda/$START/values )
            
            mkdir -p platf04/.github/workflows
            cp 02_tmp/02_pipeline/01_lambda/main.yaml $NAME.yaml
            sed -i -e "s/NAME/$NAME/g" $NAME.yaml
            cp $NAME.yaml platf04/.github/workflows/
            
            mkdir -p platf04/01_infra/lambda/$NAME

            cp 02_tmp/01_terraform/02_tfvars/01_lambda/01_terraform.tfvars terraform.tfvars
            cp 02_tmp/01_terraform/01_providers/$PROVIDER/02_provider.tf .
            sed -i -e "s/NAME/$NAME/g" terraform.tfvars
            sed -i -e "s/COUNT/$COUNT/g" terraform.tfvars
            sed -i -e "s/BUCKET/$NAME/g" 02_provider.tf
            
            # touch platf04/.github/workflows/$NAME.yaml
            cp terraform.tfvars platf04/01_infra/lambda/$NAME/terraform.tfvars
            cp 02_provider.tf platf04/01_infra/lambda/$NAME/02_provider.tf
            
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.PLAT04 }}
          with:
            source-directory: "platf04"
            destination-github-username: "maxxam123"
            destination-repository-name: "platf04"
            user-email: hennighausenmax@gmail.com
            target-branch: main

            

            # for each in $(ls cluster); do
            #   echo "THIS IS INSIDE CLUSTER"
            #   echo $each
            #   done
              
              
   
