on:
 push:
   branches:
   - main
   paths:
   # - '03_trigger/trigger'
   - '03_trigger/01_lambda_delete'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            git clone https://github.com/maxxam123/platf04.git

            NAME=$( sed -n 1p 03_trigger/01_lambda_delete )

            mkdir -p platf04/03_trigger
            echo "test" > platf04/03_trigger/test
            
            mkdir -p platf04/.github/workflows
            cp 02_tmp/02_pipeline/01_lambda/main_delete.yaml $NAME_delete.yaml
            sed -i -e "s/NAME/$NAME/g" $NAME_delete.yaml
            cp $NAME_delete.yaml platf04/.github/workflows/
            
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.PLAT04 }}
          with:
            source-directory: "platf04"
            destination-github-username: "maxxam123"
            destination-repository-name: "platf04"
            user-email: hennighausenmax@gmail.com
            target-branch: main
            
