on:
 push:
   branches:
   - main
   paths:
   - 'test/create_cluster.yaml'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            mkdir -p folder/.github/workflows
            mkdir -p folder/cluster
            
            path=/home/runner/work/platform02/platform02/cluster       
            path1=../../folder/.github/workflows
            path2=../../folder/cluster
            
            for each in $(ls $path); do
              cd $path/$each
              var=$( sed -n 1p cluster.yaml )
              provider=$( sed -n 2p cluster.yaml )
              
              cat users.yaml | wc -l > user_amount.txt
              user_amount=$( sed -n 1p user_amount.txt )
              echo "this is 1"
              
              mkdir $path1/$var
              mkdir $path2/$var

              ### PIPELINE ###
              ################
              
              #cp ../../templates/pipelines/pipeline $path1/$var.yaml
              #sed -i -e "s/xyz/$var/g" $path1/$var.yaml

              ### TERRAFORM ###
              #################
              
                ### PROVIDER
              #cp ../../templates/terraform/* $path2/$var/
                
              #cp ../../templates/terraform/01-provider.tf $path2/$var/01-provider.tf
              #sed -i -e "s/PROVIDER/$provider/g" $path2/$var/01-provider.tf
              #sed -i -e "s/BUCKET/$var/g" $path2/$var/01-provider.tf

                ### EKS
              ((user_amount++))
              echo "this is user_amount"
              echo $user_amount
              for (( i=1 ; i<$user_amount ;i++ )) ; do
                cat ../../templates/terraform/02-cluster.tf > single.tf
                sed -n "$i"p users.yaml > name.txt
                user_name=$( cat name.txt )
                sed -i -e "s/USER/$user_name/g" single.tf
                cat single.tf >> $path2/$var/03-users.tf
              done
              cat $path2/$var/03-users.tf
              
              #cp ../../templates/terraform/02-cluster.tf $path2/$var/02-cluster.tf
              #sed -i -e "s/NAME/$var/g" $path2/$var/02-cluster.tf
              
            done
