on:
 push:
   branches:
   - main
   paths:
   - 'test/create_cluster.yaml'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            mkdir -p folder/.github/workflows
            mkdir -p folder/cluster
            
            path=/home/runner/work/platform02/platform02/cluster       
            path1=../../folder/.github/workflows
            path2=../../folder/cluster
            
            for each in $(ls $path); do
              cd $path/$each

              
              var=$( sed -n 1p cluster.yaml )
              provider=$( sed -n 2p cluster.yaml )
              
              cat users.yaml | wc -l > user_amount.txt
              user_amount=$( sed -n 1p user_amount.txt )

              cat vm.yaml | wc -l > vm_amount.txt
              vm_amount=$( sed -n 1p vm_amount.txt )

              
              mkdir $path1/$var
              mkdir $path2/$var

              ### PIPELINE ###
              ################
              
              #cp ../../templates/pipelines/pipeline $path1/$var.yaml
              #sed -i -e "s/xyz/$var/g" $path1/$var.yaml

              ### TERRAFORM ###
              #################
              
                ### PROVIDER
              #cp ../../templates/terraform/* $path2/$var/
                
              #cp ../../templates/terraform/01-provider.tf $path2/$var/01-provider.tf
              #sed -i -e "s/PROVIDER/$provider/g" $path2/$var/01-provider.tf
              #sed -i -e "s/BUCKET/$var/g" $path2/$var/01-provider.tf

                ### INSTANCES
              ((vm_amount++))
              # i<$vm_amount
              for (( i=1 ; i<5 ;i++ )) ; do
                cat ../../templates/terraform/03-vm.tf > single1.tf
                #sed -n "$i"p vm.yaml > name1.txt
                #vm_name=$( cat name1.txt )
                vm_name=$( sed -n "$i"p vm.yaml )
                
                sed -i -e "s/VM/$vm_name/g" single1.tf
                cat single1.tf >> $path2/$var/02-vm.tf
              done

                ### USERS
              ((user_amount++))
              for (( i=1 ; i<$user_amount ;i++ )) ; do
                cat ../../templates/terraform/02-cluster.tf > single.tf
                #sed -n "$i"p users.yaml > name.txt
                #user_name=$( cat name.txt )
                user_name=$( sed -n "$i"p users.yaml )
                
                sed -i -e "s/USER/$user_name/g" single.tf
                cat single.tf >> $path2/$var/03-users.tf
              done
              cat $path2/$var/03-users.tf
              
              #cp ../../templates/terraform/02-cluster.tf $path2/$var/02-cluster.tf
              #sed -i -e "s/NAME/$var/g" $path2/$var/02-cluster.tf
              
            done
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
