on:
 push:
   branches:
   - main
   paths:
   # - '03_trigger/trigger'
   - '03_trigger/lambda_trigger'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            git clone https://github.com/maxxam123/platf04.git

            START=$( sed -n 1p 03_trigger/lambda_trigger )
            NAME=$( sed -n 1p 01_infra/lambda/$START/values )
            COUNT=$( sed -n 3p 01_infra/lambda/$START/values )
            PROVIDER=$( sed -n 2p 01_infra/lambda/$START/values )
            mkdir -p platf04/.github/workflows
            mkdir -p platf04/01_infra/$NAME

            cp 02_tmp/terraform/01_terraform.tfvars .
            cp 02_tmp/terraform/providers/$PROVIDER/02_provider.tf .
            # cp 02_tmp/terraform/02_provider.tf .
            sed -i -e "s/NAME/$NAME/g" 01_terraform.tfvars
            sed -i -e "s/COUNT/$COUNT/g" 01_terraform.tfvars
            sed -i -e "s/BUCKET/$NAME/g" 02_provider.tf
            
            touch platf04/.github/workflows/$NAME.yaml
            cp 01_terraform.tfvars platf04/01_infra/$NAME/01_terraform.tfvars
            cp 02_provider.tf platf04/01_infra/$NAME/02_provider.tf
            
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.PLAT04 }}
          with:
            source-directory: "platf04"
            destination-github-username: "maxxam123"
            destination-repository-name: "platf04"
            user-email: hennighausenmax@gmail.com
            target-branch: main

            

            # for each in $(ls cluster); do
            #   echo "THIS IS INSIDE CLUSTER"
            #   echo $each
            #   done
              
              
   
