
on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/01_lambda'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
            sh 04_scripts/01_lambda.sh
            
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.PLAT04 }}
          with:
            source-directory: "platf04"
            destination-github-username: "maxxam123"
            destination-repository-name: "platf04"
            user-email: hennighausenmax@gmail.com
            target-branch: main
            
           
