
on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/01_lambda'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
            sh 04_scripts/01_lambda.sh
            
           
