on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            pwd
            mkdir folder
            mkdir folder/sync2
            cd folder
            git clone https://github.com/maxxam123/platform01
            ls -la
            rm -rf platform01
            mkdir .github
            mkdir tf
            mkdir .github/workflows
            cd ..
            
            path=/home/runner/work/platform02/platform02/cluster
            #path=/home/runner/work/platform02/platform02/sync2
            
            for each in $(ls $path); do
              cd $path/$each
              var=$( cat abc.yaml)
              echo $var
              mkdir ../../folder/.github/workflows/$var
              mkdir ../../folder/tf/$var
              cp ../../pipeline/tmp ../../folder/.github/workflows/$var.yaml
              sed -i -e "s/xyz/$var/g" ../../folder/.github/workflows/$var.yaml
              
              cp ../../pipeline/tmp2 ../../folder/tf/$var/abc.yaml
              sed -i -e "s/xyz2/$var/g" ../../folder/tf/$var/abc.yaml
              
              ls 
            done
            
            cd ../..

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
