on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            mkdir folder
            mkdir folder/sync2
            cd folder
            git clone https://github.com/maxxam123/platform01
            diff -r platform01/sync2/ ../sync/ > diff.yaml
            cat diff.yaml
            ls -la
            rm -rf platform01
            mkdir .github
            mkdir .github/workflows
            cd ..
            
            cp pipeline/template.yaml folder/.github/workflows/template.yaml
            
            cp sync/* folder/sync2/
            cd ..

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
