on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            mkdir -p folder/.github/workflows
            mkdir -p folder/cluster
            mkdir -p folder/gitops
            
            path=/home/runner/work/platform02/platform02/cluster
            
            path1=../../folder/.github/workflows
            path2=../../folder/cluster
            path3=../../folder/gitops
            
            for each in $(ls $path); do
              cd $path/$each
              var=$( sed -n 1p cluster.yaml)
              ami=$( sed -n 2p cluster.yaml)
              ins=$( sed -n 3p cluster.yaml)
              sub=$( sed -n 4p cluster.yaml)
              acc=$( sed -n 6p cluster.yaml)
              sec=$( sed -n 7p cluster.yaml)
              buc=$( sed -n 8p cluster.yaml)
              
              mkdir $path1/$var
              mkdir $path2/$var
              mkdir $path3/$var
              
              cp ../../pipeline/tmp $path1/$var.yaml
              sed -i -e "s/xyz/$var/g" $path1/$var.yaml
              sed -i -e "s/acc/$acc/g" $path1/$var.yaml
              sed -i -e "s/secc/$sec/g" $path1/$var.yaml
              sed -i -e "s/buc/$buc/g" $path1/$var.yaml
              
              cp ../../pipeline/tmp2 $path2/$var/cluster.yaml
              sed -i -e "s/NAME/$var/g" $path2/$var/cluster.yaml
              sed -i -e "s/AMI/$ami/g" $path2/$var/cluster.yaml
              sed -i -e "s/INS/$ins/g" $path2/$var/cluster.yaml
              sed -i -e "s/SUB/$sub/g" $path2/$var/cluster.yaml

              cp ../../pipeline/tmp3 $path3/$var.yaml
              sed -i -e "s/NAME/$var/g" $path3/$var.yaml
              
            done

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
