on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            pwd
            mkdir folder
            mkdir folder/sync2
            cd folder
            git clone https://github.com/maxxam123/platform01
            ls -la
            rm -rf platform01
            mkdir .github
            mkdir .github/workflows
            cd ..
            
            path=/home/runner/work/platform02/platform02/sync2
            
            for each in $(ls $path); do
              cd $path/$each
              var=$( cat new1.yaml)
              echo $var
              mkdir ../../folder/.github/workflows/$var
              cp ../../pipeline/tmp ../../folder/.github/workflows/$var/tmp
              sed -i -e "s/xyz/$var/g" ../../folder/.github/workflows/$var/tmp
              cat ../../folder/.github/workflows/$var/tmp
              ls 
            done
            
            cd ../..
