on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            mkdir -p folder/.github/workflows
            mkdir -p folder/cluster
            
            path=/home/runner/work/platform02/platform02/cluster
            path1=../../folder/.github/workflows
            path2=../../folder/cluster
            
            for each in $(ls $path); do
              cd $path/$each
              var=$( cat cluster.yaml)
              mkdir $path1/$var 
              mkdir $path2/$var
              cp ../../pipeline/tmp $path1/$var.yaml
              sed -i -e "s/xyz/$var/g" $path1/$var.yaml
              
              cp ../../pipeline/tmp2 $path2/$var/cluster.yaml
              sed -i -e "s/xyz2/$var/g" $path2/$var/cluster.yaml
            done

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
