on:
 push:
   branches:
   - main
   paths:
   - 'test/**'
   
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: |
            ls
            cd home
            ls -la
            

            
