on:
 push:
   branches:
   - main
   paths:
   - 'test/**'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
            mkdir folder
            cd folder
            git clone https://github.com/maxxam123/platform01
            mkdir .github
            cd .github
            mkdir workflows
            cd workflows
            echo "on:" >> pipeline.yaml
            echo "  push:" >> pipeline.yaml
            echo "    branches:" >> pipeline.yaml
            echo "    - main" >> pipeline.yaml
            echo "jobs:" >> pipeline.yaml
            echo "  build:" >> pipeline.yaml
            echo "    runs-on: ubuntu-latest" >> pipeline.yaml
            echo "    steps:" >> pipeline.yaml
            echo "      - uses: actions/checkout@v3" >> pipeline.yaml
            echo "      - name: test" >> pipeline.yaml
            echo "        run: |" >> pipeline.yaml
            echo "          ls -la" >> pipeline.yaml
            cd ../../..

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
