on:
 push:
   branches:
   - main
   paths:
   - 'test2'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            var=$( sed -n 1p test2 )
            echo $var
            mkdir -p folder/$var
            echo $var > folder/$var/test

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.PLAT04 }}
          with:
            source-directory: "folder"
            destination-github-username: "maxxam123"
            destination-repository-name: "platf04"
            user-email: hennighausenmax@gmail.com
            target-branch: main

            

            # for each in $(ls cluster); do
            #   echo "THIS IS INSIDE CLUSTER"
            #   echo $each
            #   done
              
              
   
