on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/test'
   
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |

            sh 04_scripts/test.sh
